version: '3'
services:
  cache:
    image: redis:7.0.8-alpine
    container_name: automation-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local